# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Coyote Flaco Mexican Restaurant | Connecticut
email: 
description: >- # this means to ignore newlines until "baseurl:"
  We have great food like burritos, fajitas, tacos, quesadillas, tamales and great margaritas. During the summer we have outdoor seating. You can visit us in Hartford, CT and we Deliver call us at (860) 953-1299. Or you can visit our Mansfield, CT near the Uconn Storr's campus at (860) 423-4414. 635 New Britain Ave, Hartford, CT, 860-953-1299, - 50 Higgins Hwy, Mansfield, CT 860-423-4414.
hartford: >-
   Located in Hartford’s quiet southwest, we’ve been serving up quality Mexican food straight from our parents’ recipes since 1999. We make great margaritas and, when the weather is nice, you can enjoy dinner and drinks on the patio. Off-street parking is available in the front, in back and on the side of our building. 
   Here’s what some of our customers have to say.
mansfield: >-
  Located in Storrs, near the UCONN campus, we’ve been serving up quality Mexican food straight from our parents’ recipes since 1999. We make great margaritas and, when the weather is nice, you can enjoy dinner and drinks on the patio.
  Here’s what some of our customers have to say.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://coyoteflacoct.com" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: 
# github_username:  
timezone: America/New_York
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-minifier
  - jekyll-autoprefixer
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-analytics

#CSS
auotprefixer:
    browsers:
      -last 2 versions
      # only_production: true

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-42573959-1          # Required - replace with your tracking id
    anonymizeIp: true      # Optional - Default: false - set to true for anonymized tracking

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

permalink: pretty

jekyll_admin:
  hidden_links:
    - posts
    # - pages
    # - staticfiles
    # - datafiles
    # - configuration

jekyll-sitemap: 
  sitemap: true

jekyll-minifier:
  exclude: 'atom.xml'

jekyll-minifier:
preserve_php: true                # Default: false
remove_spaces_inside_tags: true   # Default: true
remove_multi_spaces: true         # Default: true
remove_comments: true             # Default: true
remove_intertag_spaces: true      # Default: false
remove_quotes: false              # Default: false
compress_css: true                # Default: true
compress_javascript: true         # Default: true
simple_doctype: false             # Default: false
remove_script_attributes: false   # Default: false
remove_style_attributes: false    # Default: false
remove_link_attributes: false     # Default: false
remove_form_attributes: false     # Default: false
remove_input_attributes: false    # Default: false
remove_javascript_protocol: false # Default: false
remove_http_protocol: false       # Default: false
remove_https_protocol: false      # Default: false
preserve_line_breaks: false       # Default: false
simple_boolean_attributes: false  # Default: false
compress_js_templates: false      # Default: false
uglifier_args:
    harmony: true

sass:
  style: compressed